---
type: showroom
default_width: 50
persist_url_state: true

tabs:
  - name: Terminal
    path: /wetty
    port: 443
  - name: OCP Console
    url: 'https://console-openshift-console.${DOMAIN}'
  - name: RHBK
    url: 'https://sso.${DOMAIN}' 
  - name: RHTPA
    url: 'https://server-tssc-tpa.${DOMAIN}'
  - name: REKOR Search UI
    url: 'https://rekor-search-ui-tssc-tas.${DOMAIN}'
  - name: Quay
    url: 'https://quay-${GUID}.${DOMAIN}'
  - name: Gitlab
    url: 'https://gitlab-gitlab.${DOMAIN}'
  - name: RHDH
    url: 'https://backstage-backstage.${DOMAIN}'
  - name: ARGOCD
    url: 'https://argocd-server-tssc-gitops.${DOMAIN}'
  - name: ACS
    url: 'https://central-stackrox.${DOMAIN}'
